/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "idenbridjpcareerapi",
            "endpoint": "https://etkd6zi59b.execute-api.ap-northeast-1.amazonaws.com/dev",
            "region": "ap-northeast-1"
        },
        {
            "name": "idenbridjpcontactus",
            "endpoint": "https://s78yreeyz0.execute-api.ap-northeast-1.amazonaws.com/dev",
            "region": "ap-northeast-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "ap-northeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "idenbridjpcareer-dev",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "idenbridjpcontactus-dev",
            "region": "ap-northeast-1"
        }
    ]
};


export default awsmobile;
